// GENERATED by scripts/sync-blog.mjs — do not edit. Add articles as JSON in src/content/blog/.
import type { BlogPost } from "./blog";
import post_porcelain_veneers_cost_miami from "@/content/blog/porcelain-veneers-cost-miami.json";
import post_porcelain_veneers_cost_miami_es from "@/content/es/blog/porcelain-veneers-cost-miami.json";

export const postsEn: BlogPost[] = [post_porcelain_veneers_cost_miami as BlogPost];
export const postsEs: BlogPost[] = [post_porcelain_veneers_cost_miami_es as BlogPost];
