// Registers every article in src/content/blog/*.json (English) and its Spanish
// twin in src/content/es/blog/ : writes the import registry (src/lib/blog.gen.ts),
// the route list (src/content/blog-posts.json) and the page metadata entries in
// pages.json / es/pages.json so routes, sitemap, hreflang and checks all see them.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";

const dir = "src/content/blog";
const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".json")).sort() : [];
const posts = files.map((f) => {
  const en = JSON.parse(readFileSync(`${dir}/${f}`, "utf8"));
  const esFile = `src/content/es/blog/${f}`;
  const es = existsSync(esFile) ? JSON.parse(readFileSync(esFile, "utf8")) : null;
  for (const [k, v] of Object.entries({ slug: en.slug, esSlug: en.esSlug, title: en.title, description: en.description, author: en.author, datePublished: en.datePublished, image: en.image, answer: en.answer }))
    if (!v) throw new Error(`${f}: missing "${k}"`);
  if (en.slug !== f.replace(/\.json$/, "")) throw new Error(`${f}: slug must equal the file name`);
  return { file: f, en, es };
});

const ident = (s) => "post_" + s.replace(/[^a-zA-Z0-9]/g, "_");
let ts = `// GENERATED by scripts/sync-blog.mjs — do not edit. Add articles as JSON in src/content/blog/.\nimport type { BlogPost } from "./blog";\n`;
for (const p of posts) {
  ts += `import ${ident(p.en.slug)} from "@/content/blog/${p.file}";\n`;
  if (p.es) ts += `import ${ident(p.en.slug)}_es from "@/content/es/blog/${p.file}";\n`;
}
ts += `\nexport const postsEn: BlogPost[] = [${posts.map((p) => `${ident(p.en.slug)} as BlogPost`).join(", ")}];\n`;
ts += `export const postsEs: BlogPost[] = [${posts.map((p) => (p.es ? `${ident(p.en.slug)}_es as BlogPost` : `${ident(p.en.slug)} as BlogPost`)).join(", ")}];\n`;
writeFileSync("src/lib/blog.gen.ts", ts);

writeFileSync(
  "src/content/blog-posts.json",
  JSON.stringify(posts.map((p) => ({ slug: p.en.slug, esSlug: p.en.esSlug, treatments: p.en.treatments ?? [], datePublished: p.en.datePublished, dateModified: p.en.dateModified ?? p.en.datePublished })), null, 2) + "\n",
);

// Page metadata entries (keys are English paths; Spanish file holds the Spanish meta)
for (const [file, lang] of [["src/content/pages.json", "en"], ["src/content/es/pages.json", "es"]]) {
  const pages = JSON.parse(readFileSync(file, "utf8"));
  for (const key of Object.keys(pages)) if (key.startsWith("/blog/")) delete pages[key];
  for (const p of posts) {
    const src = lang === "es" && p.es ? p.es : p.en;
    pages[`/blog/${p.en.slug}`] = { title: src.seoTitle ?? src.title, description: src.description, ogImage: src.image, h1: src.title, breadcrumb: src.breadcrumb ?? src.title };
  }
  writeFileSync(file, JSON.stringify(pages, null, 2) + "\n");
}
console.log(`blog: ${posts.length} article(s) registered`);
